name = "NnSurvival"
author = "nnra6864"
version = "1.0.0"
pack-format = "packwiz:1.1.0"

[index]
file = "index.toml"
hash-format = "sha256"
hash = "091c4e1b03ca7e4a9b0d1f225334e46bee97b6bb82567f4b984b2ba7efafecb3"

[versions]
fabric = "0.19.5"
minecraft = "26.3"

[options]
acceptable-game-versions = ["26.2"]
