name = "NnSurvival"
author = "nnra6864"
version = "1.0.0"
pack-format = "packwiz:1.1.0"

[index]
file = "index.toml"
hash-format = "sha256"
hash = "3ce1d5aeb9c8ede031fa41101bc3acf68a0610cec10e40144289c7cf4ba27a26"

[versions]
fabric = "0.19.5"
minecraft = "26.3"

[options]
acceptable-game-versions = ["26.2"]
