name = "NnSurvival"
author = "nnra6864"
version = "1.0.0"
pack-format = "packwiz:1.1.0"

[index]
file = "index.toml"
hash-format = "sha256"
hash = "9b843e989302199e8b51347b80d2e3640b395e77d479dc5964bd79b3a8a6fee6"

[versions]
fabric = "0.19.5"
minecraft = "26.3"

[options]
acceptable-game-versions = ["26.2"]
