#This file stores configuration options for Iris, such as the currently active shaderpack
#Tue Oct 06 01:23:17 CEST 2026
allowUnknownShaders=false
colorSpace=SRGB
disableUpdateMessage=false
enableDebugOptions=false
enableShaders=true
maxShadowRenderDistance=32
shaderPack=Eclipse-Shader-Unstable.zip
